### ISSUE TITLE
ArchLinux : How to fix build errors

### ISSUE THREAD

**Issue by noraj** [php-build/php-build#591]
## Issue

```
$ phpenv install 5.6.40       
[Info]: Loaded extension plugin
[Info]: Loaded apc Plugin.
[Info]: Loaded composer Plugin.
[Info]: Loaded github Plugin.
[Info]: Loaded uprofiler Plugin.
[Info]: Loaded xdebug Plugin.
[Info]: Loaded xhprof Plugin.
[Info]: Loaded zendopcache Plugin.
[Info]: php.ini-production gets used as php.ini
[Info]: Building 5.6.40 into /home/noraj/.phpenv/versions/5.6.40
[Downloading]: https://secure.php.net/distributions/php-5.6.40.tar.bz2
[Preparing]: /tmp/php-build/source/5.6.40

-----------------
|  BUILD ERROR  |
-----------------

Here are the last 10 lines from the log:

-----------------------------------------
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
configure: error: mcrypt.h not found. Please reinstall libmcrypt.
-----------------------------------------

The full Log is available at '/tmp/php-build.5.6.40.20191011112233.log'.
[Warn]: Aborting build.
```

## Solution

ArchLinux:

```
$ sudo pacman -S re2c libmcrypt --needed --asdeps
```

---

## Issue

```
$ phpenv install 5.6.40                          
[Info]: Loaded extension plugin
[Info]: Loaded apc Plugin.
[Info]: Loaded composer Plugin.
[Info]: Loaded github Plugin.
[Info]: Loaded uprofiler Plugin.
[Info]: Loaded xdebug Plugin.
[Info]: Loaded xhprof Plugin.
[Info]: Loaded zendopcache Plugin.
[Info]: php.ini-production gets used as php.ini
[Info]: Building 5.6.40 into /home/noraj/.phpenv/versions/5.6.40
[Skipping]: Already downloaded and extracted https://secure.php.net/distributions/php-5.6.40.tar.bz2
[Preparing]: /tmp/php-build/source/5.6.40

-----------------
|  BUILD ERROR  |
-----------------

Here are the last 10 lines from the log:

-----------------------------------------
configure: error: Cannot find libtidy
-----------------------------------------

The full Log is available at '/tmp/php-build.5.6.40.20191011112532.log'.
[Warn]: Aborting build.
```

## Solution

```
$ sudo pacman -S tidy --needed --asdeps
```

---

## Issue

```
$ phpenv install 5.6.40                    
[Info]: Loaded extension plugin
[Info]: Loaded apc Plugin.
[Info]: Loaded composer Plugin.
[Info]: Loaded github Plugin.
[Info]: Loaded uprofiler Plugin.
[Info]: Loaded xdebug Plugin.
[Info]: Loaded xhprof Plugin.
[Info]: Loaded zendopcache Plugin.
[Info]: php.ini-production gets used as php.ini
[Info]: Building 5.6.40 into /home/noraj/.phpenv/versions/5.6.40
[Skipping]: Already downloaded and extracted https://secure.php.net/distributions/php-5.6.40.tar.bz2
[Preparing]: /tmp/php-build/source/5.6.40
[Compiling]: /tmp/php-build/source/5.6.40

-----------------
|  BUILD ERROR  |
-----------------

Here are the last 10 lines from the log:

-----------------------------------------
      |             ^~~~~~
/tmp/php-build/source/5.6.40/ext/openssl/openssl.c: In function ‘zif_openssl_encrypt’:
/tmp/php-build/source/5.6.40/ext/openssl/openssl.c:5233:17: error: storage size of ‘cipher_ctx’ isn’t known
 5233 |  EVP_CIPHER_CTX cipher_ctx;
      |                 ^~~~~~~~~~
/tmp/php-build/source/5.6.40/ext/openssl/openssl.c: In function ‘zif_openssl_decrypt’:
/tmp/php-build/source/5.6.40/ext/openssl/openssl.c:5316:17: error: storage size of ‘cipher_ctx’ isn’t known
 5316 |  EVP_CIPHER_CTX cipher_ctx;
      |                 ^~~~~~~~~~
make: *** [Makefile:682: ext/openssl/openssl.lo] Error 1
-----------------------------------------

The full Log is available at '/tmp/php-build.5.6.40.20191011112844.log'.
[Warn]: Aborting build.
```

## Solution

```
$ sudo pacman -S openssl-1.0
$ CONFIGURE_OPTS="--with-openssl=/usr/include/openssl-1.0/" phpenv install 5.6.40
```

---

## Issue

```
$ CONFIGURE_OPTS="--with-openssl=/usr/include/openssl-1.0/" phpenv install 5.6.40
[Info]: Loaded extension plugin
[Info]: Loaded apc Plugin.
[Info]: Loaded composer Plugin.
[Info]: Loaded github Plugin.
[Info]: Loaded uprofiler Plugin.
[Info]: Loaded xdebug Plugin.
[Info]: Loaded xhprof Plugin.
[Info]: Loaded zendopcache Plugin.
[Info]: php.ini-production gets used as php.ini
[Info]: Building 5.6.40 into /home/noraj/.phpenv/versions/5.6.40
[Skipping]: Already downloaded and extracted https://secure.php.net/distributions/php-5.6.40.tar.bz2
[Preparing]: /tmp/php-build/source/5.6.40

-----------------
|  BUILD ERROR  |
-----------------

Here are the last 10 lines from the log:

-----------------------------------------
configure: error: Cannot find OpenSSL's <evp.h>
-----------------------------------------

The full Log is available at '/tmp/php-build.5.6.40.20191011114648.log'.
```

## Solution

Can't build with openssl 1.1, 1.0 and 0.9.8.

**Comment by GrahamCampbell** [comment]
Stale.

**Comment by noraj** [comment]
lol
